name: weeidl
description: "Chipi chipi chappa chappa"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.2.3
  flutter: ^3.16.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_svg: 2.0.8
  gap: ^3.0.1
  flutter_bloc: ^8.1.3
  auto_size_text: 3.0.0
  lottie: ^3.1.0
  o3d: ^3.1.0
  url_launcher: ^6.2.6
  go_router: ^13.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/social/
    - assets/mac_window/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
